### ISSUE TITLE
Role of probe_resistance

### ISSUE THREAD

**Issue by yyiwu** [caddyserver/forwardproxy#104]
What is the domain name added after probe_resistance used for? Is it the domain name that is accessed only when the user name and password are incorrect?

**Comment by mholt** [comment]
It's a "secret link" that if you visit it, will prompt your client for authentication. It is needed if your client does not send authentication on its own.

**Comment by yyiwu** [comment]
> It's a "secret link" that if you visit it, will prompt your client for authentication. It is needed if your client does not send authentication on its own.
How do I access a [Baidu domain](www.baidu.com) name if it is added to probe_resistance

**Comment by mholt** [comment]
Typically you need to have control over the domain.

(Sorry, I am not much help there. You might want to get feedback from someone else who lives in China.)

**Comment by yyiwu** [comment]
> 通常，您需要控制域。
> 
> （抱歉，我帮不上什么忙。您可能想从住在中国的其他人那里获得反馈。）

Thank you very much for your answer
