### ISSUE TITLE
upstream configuration of socks5 (cloudflaer warp socks5)

### ISSUE THREAD

**Issue by kakahu2021** [caddyserver/forwardproxy#143]
In the past, the upstream upstream configuration of socks5 (cloudflaer warp socks5) could proxy normally, but after warp-svc reached version 2024.6.497, it could not proxy normally.

**Comment by kakahu2015** [comment]
Forward proxy stops working after WARP service upgrade to 2024.9.346.0

Previously, with this configuration:
route {
    forward_proxy {
        basic_auth user1 0NtCL2JPJBgPPMmlPcJ 
        ports     80 443
        hide_ip
        hide_via
        probe_resistance secret-link-kWWL9Q.com
        upstream socks5://127.0.0.1:40000
    }
    file_server
}

After upgrading WARP service to version 2024.9.346.0, the proxy stopped working. The WARP socks service is still running on port 40000.

**Comment by kakahu2021** [comment]
It's not a forwardproxy problem it's a warp-svc version problem.https://community.cloudflare.com/t/cloudflare-warp-version-2024-9-346-0-proxy-mode-issue/720751/28
