### ISSUE TITLE
docker build fails

### ISSUE THREAD

**Issue by pwFoo** [caddyserver/forwardproxy#2]
Plugin isn't available?
````
Downloading Caddy for linux/amd64...
https://caddyserver.com/download/linux/amd64?plugins=http.forwardproxy
curl: (22) The requested URL returned error: 400 Bad Request
Aborted, error 22 in command: curl -fsSL "$caddy_url" -o "$dl"
The command '/bin/sh -c curl --fail https://getcaddy.com | bash -s http.forwardproxy' returned a non-zero code: 1
```

**Comment by mholt** [comment]
The plugin is not available on the build server until Caddy 0.10.7 is released. For now, you'll have to plug it in yourself and build from source. Fortunately, it's pretty simple. Here's how: https://github.com/mholt/caddy/wiki/Plugging-in-Plugins-Yourself
