### ISSUE TITLE
readfrom tcp [redacted]:35832->173.194.22.38:443: stream error: stream ID 187; CANCEL

### ISSUE THREAD

**Issue by allenchennnn** [caddyserver/forwardproxy#23]
？？？？

**Comment by sergeyfrolov** [comment]
Please do not delete the issue template, and explain the circumstances under which the error has happened and how can I reproduce it.
In general, this error might be and quite often is and quite often an indication of graceful connection shutdown, so there's nothing to worry about. Unless you've got any more relevant information, I'll have this issue closed.
P.S. tried redacting your IP address in the title. Unfortunately, there seems no way
