### ISSUE TITLE
It does not work with authorization 

### ISSUE THREAD

**Issue by pingma** [caddyserver/forwardproxy#25]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.11.0 (non-commercial use only)

### 2. What are you trying to do?
to forward a https proxy

### 3. What is your entire Caddyfile?
```text
(paste Caddyfile here)
```
example.com ## My site
gzip
log /var/log/caddy/access.log
root /usr/share/www

forwardproxy {
   basicauth user passwd
   hide_ip
   probe_resistance secretlink.localhost
}

### 4. How did you run Caddy (give the full command and describe the execution environment)?
caddy -c /etc/caddy.conf

### 6. What did you expect to see?
chrome + swithyomega can surf the web through the proxy WITH AN AUTHORIZATION

### 7. What did you see instead (give full error messages and/or log)?
It works well when there is no Authorization. However, when i add the "basicauth user passwd" in the caddy file, and fill the same user/passwd in the switchyomega configuration, it does not work. 

This is the log from caddy:
28/May/2018:06:55:03 +0100 [ERROR 0 ] Proxy-Authorization is required! Expected format: <type> <credentials>

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
1, set "basicauth user passwd" in caddy configuration;
2, fill the same user/password in switchyomega configuration;
3, browser some sites with the proxy, and it just cannot work.

**Comment by pingma** [comment]
I have figured it out. Close it.

**Comment by sergeyfrolov** [comment]
I highly recommend to choose unique secret link, so that censor could not possibly probe your server
```
probe_resistance myownlink123.localhost
```
