### ISSUE TITLE
指定流量使用上游代理

### ISSUE THREAD

**Issue by allenchennnn** [caddyserver/forwardproxy#28]
我有一台韩国VPS,并成功搭建了代理，韩国也有墙，不能访问某些小姐姐网站。怎么把只访问小姐姐的流量转发到香港VPS上处理呢？

**Comment by mholt** [comment]
Hi there,

I have plugged this into Google Translate because I don't know Chinese. For convenience of others, here is the translation:

> Specify upstream traffic using upstream proxy
>
> I have a South Korean VPS and have successfully built an agent. South Korea also has a wall and cannot visit certain Miss Sister websites. How do you forward the traffic to the Missy Sister to the Hong Kong VPS?

**Comment by sergeyfrolov** [comment]
@allenchennnn this is a forum for developers, please seek support at https://caddy.community
To ensure people understand what exactly you are asking, spell it out extremely verbosely, and include translation by Google Translate.
If I did understand you correctly, It sounds like it's related to upstream proxy that is a work in progress #27. However, upstream proxy will not have functionality to limit what is being upstreamed: it is either all traffic or nothing.
