### ISSUE TITLE
got 502 error when accessing http sites

### ISSUE THREAD

**Issue by qazesz1** [caddyserver/forwardproxy#36]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.11.0 (non-commercial use only)

### 2. What are you trying to do?
Use forwardproxy plugin to serve as a forward proxy.

### 3. What is your entire Caddyfile?
```text
*.* {
 timeouts none
 tls *@*
 header / Strict-Transport-Security "max-age=31536000;"
# ...
 gzip
# ...
 proxy /ws 127.0.0.1:9613 {
  websocket
  header_upstream -Origin
 }
 forwardproxy {
  basicauth user passwd
  hide_ip
  hide_via
#  probe_resistance secretlink.localhost
  response_timeout 10
  dial_timeout     10
 }
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
./caddy --conf=/usr/local/caddy/Caddyfile -agree 
centos 6.9 x64

### 7. What did you see instead (give full error messages and/or log)?
When I access https sites over the https proxy, it works fine. But for http site it shows `502 Bad Gateway` in broswer. 
Caddy's log here
`01/Jul/2018:08:40:45 -0400 [ERROR 502 /favicon.ico] dial  failed: Lookup of  fai                                                                             led: lookup : no such host
01/Jul/2018:08:40:46 -0400 [ERROR 502 /] dial  failed: Lookup of  failed: lookup                                                                              : no such host
01/Jul/2018:08:40:51 -0400 [ERROR 502 /] dial  failed: Lookup of  failed: lookup                                                                              : no such host
01/Jul/2018:08:40:53 -0400 [ERROR 502 /image] dial  failed: Lookup of  failed: l                                                                             ookup : no such host
01/Jul/2018:08:40:54 -0400 [ERROR 502 /image] dial  failed: Lookup of  failed: l                                                                             ookup : no such host
01/Jul/2018:08:40:54 -0400 [ERROR 502 /image] dial  failed: Lookup of  failed: l                                                                             ookup : no such host
01/Jul/2018:08:40:54 -0400 [ERROR 502 /image] dial  failed: Lookup of  failed: l                                                                             ookup : no such host
01/Jul/2018:08:40:54 -0400 [ERROR 502 /image] dial  failed: Lookup of  failed: l                                                                             ookup : no such host
01/Jul/2018:08:40:54 -0400 [ERROR 502 /image] dial  failed: Lookup of  failed: l                                                                             ookup : no such host
01/Jul/2018:08:40:54 -0400 [ERROR 502 /image] dial  failed: Lookup of  failed: l                                                                             ookup : no such host
`
What surprised me most is that I have tested an exactly same caddyfile(except domain) on another server , also with caddy 0.11.0, and nothing like this happend.

**Comment by sergeyfrolov** [comment]
Does that happen for all HTTP hosts or for particular few?
Evidently, it fails to DNS resolve the host you're trying to access. You seem to have redacted the host away, so I can't tell why this would happen.
You can try to run `dig your-http-host.com` on that machine and see if it's resolvable and if the resolved address is correct. Perhaps, it gets DNS poisoned?

**Comment by qazesz1** [comment]
Yes, as long as http sites it reports 502.
My host website on this server is absolutely accessible.
With your direction, I type './caddy -host my.host'
It returns
> Activating privacy features... done.
> https://my.host
> http://my.host

Looks good, right? Then I visit a http site, for example http://earthquake.usgs.gov/ over forwardproxy, it says
> 02/Jul/2018:21:17:20 -0400 [ERROR 502 /] dial  failed: Lookup of  failed: lookup : no such host
> 02/Jul/2018:21:17:20 -0400 [ERROR 502 /favicon.ico] dial  failed: Lookup of  failed: lookup : no such host

**Comment by qazesz1** [comment]
It seems like forwardproxy regards the http site I visit is under my domain, `http://a.com/b.html` as `my.host/b.html`

**Comment by sergeyfrolov** [comment]
Bug is fixed (updated version is available on caddyserver.com)
