### ISSUE TITLE
Can't access Tor hidden service using a Tor upstream

### ISSUE THREAD

**Issue by l5h5t7** [caddyserver/forwardproxy#39]
### 1. What version of Caddy are you using (`caddy -version`)?

Caddy 0.11.0

### 2. What are you trying to do?

Access Tor Hidden Service though Caddy (use Tor as upstream).

### 3. What is your entire Caddyfile?
```
mydomain.com {
	forwardproxy {
		hide_ip
		hide_via
		upstream socks5://localhost:9050
	}
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

Follow https://github.com/mholt/caddy/blob/master/dist/init/linux-systemd/caddy.service , use Ubuntu 18.04 LTS.

### 5. Please paste any relevant HTTP request(s) here.

```
:authority: 3cvpkfx4gdnkcduj.onion
:method: GET
:path: /
:scheme: http
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
accept-encoding: gzip, deflate
accept-language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7
cache-control: max-age=0
dnt: 1
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3472.3 Safari/537.36
```

### 6. What did you expect to see?

I can access the Tor Hidden Service.

### 7. What did you see instead (give full error messages and/or log)?

Browser: `502 Bad Gateway`
Server(time is removed):
```
[ERROR 502 /] dial  failed: socks connect tcp: missing port in address
[ERROR 0 ] readfrom tcp 127.0.0.1:21728->127.0.0.1:9050: stream error: stream ID 15; CANCEL
[ERROR 0 ] readfrom tcp 127.0.0.1:21720->127.0.0.1:9050: stream error: stream ID 11; CANCEL
[ERROR 0 ] readfrom tcp 127.0.0.1:21724->127.0.0.1:9050: stream error: stream ID 13; CANCEL
[ERROR 502 /favicon.ico] dial  failed: socks connect tcp: missing port in address
[ERROR 0 ] readfrom tcp 127.0.0.1:21732->127.0.0.1:9050: stream error: stream ID 17; CANCEL
```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

Use Tor as upstream, and access a Tor Hidden Service(Accessing clearnet sites using Tor upstream works well).

**Comment by l5h5t7** [comment]
Follow https://sfrolov.io/2017/08/secure-web-proxy-client-en#google-chromechromium , I use [Proxy Swithcy Omega](https://chrome.google.com/webstore/detail/proxy-switchyomega/padekgcemlokbadohgkifijomclgjgif).

**Comment by sergeyfrolov** [comment]
Just noticed your edit:
> (Accessing clearnet sites using Tor upstream works well).
Interesting.

First and foremost: is your forwardproxy updated to the latest version? Please do that first and see if that helps, since there was a bug related to "missing port in address". If that doesn't help, try specifying any port explicitly in the browser.

Chrome is not designed functionally for this, and there's a chance it won't be able to open such links at all. Chrome also completely defeats Tor anonymity guarantees, so I feel obliged to recommend to use Tor Browser, if you care about anonymity.
