### ISSUE TITLE
DNS Cache

### ISSUE THREAD

**Issue by pwFoo** [caddyserver/forwardproxy#4]
Will caddy / forwardproxy cache dns requests?

I changed /etc/hosts during calls. Lookup is fine local, but caddy forwardproxy use the old ip address instead of the new one.

Disable caddy / forwardproxy dns cache would be great for my use case.
Is it plugin or caddy related?

**Comment by sergeyfrolov** [comment]
Did you change `/etc/hosts` on your personal machine, or on the one that runs forwardproxy? DNS lookup is performed by the forwardproxy'ing server only.

**Comment by pwFoo** [comment]
I changed the /etc/hosts on the forwardproxy machine, not the local client.

Also a caddy restart have no effect to the dns result of the next request to the proxy. So also a caddy restart isn't force a /etc/hosts reread?

**Comment by mholt** [comment]
What do you mean by "caddy restart" - SIGUSR1 or stopping/starting the binary? SIGUSR1 just reloads the Caddyfile.

**Comment by pwFoo** [comment]
Not a reload. I stop / kill caddy process and start it again with:
```
caddy -log stdout -conf caddyfile 
```

After interrupt the command no caddy process is running. So it should be a full restart.

**Comment by pwFoo** [comment]
After some more testing.
It's dependent on dns order. caddy (or proxy machine?) try to use dns before /etc/hosts. So host enty won't work if a public dns entry exists.

So it also could be host dependent instead of caddy / forwardproxy... I'll check that.

**Comment by pwFoo** [comment]
I think it's really nsswitch.conf related. So it shouldn't be a caddy / forwardproxy issue...

Thanks!

**Comment by l5h5t7** [comment]
According to [this](https://golang.org/pkg/net/#hdr-Name_Resolution) description, on Unix systems, forwardproxy will use a pure Go resolver by default, which is doesn't follow `/etc/hosts`, set `GODEBUG` to `netdns=cgo` may solve this issue.
