### ISSUE TITLE
Add HTTP/2 support for connecting to upstream proxy server

### ISSUE THREAD

**Issue by joeshae** [caddyserver/forwardproxy#45]
Currently, if the upstream proxy server supports only HTTP/2, forwardproxy can not work with it.
Could you please add support for connecting to HTTP/2 upstream proxy server?
Thank you!

**Comment by sergeyfrolov** [comment]
It's added! On top of simple http2 support, it _should_ also multiplex the connections, reducing number of connections (which helps staying under the radar of network adversaries), and providing benefits in performance.
@joeshae would you be able to try it out and tell me if it works (or doesn't)?

**Comment by joeshae** [comment]
Hello @sergeyfrolov ,

In my tests, there are two HTTP2 proxy servers: 
one is commercial HTTP2 proxy server (A), and the other one is forwardproxy HTTP2 proxy server (B). 
BTW, server (A) is not forwardproxy.

If the web page I was browsing has **A LOT OF** elements, eg: http://www.dmm.com/digital/videomarket/movie/-/list/=/article=genre/id=5/sort=date/

Test A: Only Server (A) is used. I was connecting to server (A) via HTTP2.
Result: The page loading is fast. I can see many elements loaded nearly simultaneously every few seconds.

Test B: Server (A) is used as the upstream server of server (B), they talk with each other in HTTP2. And I was connecting to server (B) via HTTP2.
Result: Obviously slower than Test A. I can see only 4-8 elements loaded simultaneously every few seconds. Some elements loaded failed the first time occasionally.

After lots of tests, I think some HTTP2 parameters in forwardproxy might need to be optimized to improve the performance. 
I've heard that there are some HTTP2 parameters can determine how many concurrent requests share a HTTP2 connection, and some other parameters can determine how many times each connection can be reused.

Perhaps, one option is trying to optimize these parameters to be best as we can, 
and one more option, which might be better, is exposing these HTTP2 parameters to users with default value suggestions.

How do you think about it?

**Comment by sergeyfrolov** [comment]
@joeshae I have deployed a performance improvement. Please check it out, and submit a new issue, if the problem persists.
I must say, however, that even before a patch performance of my upstream setup consisting of 2 forwardproxies was better, than "only 4-8 elements loaded simultaneously every few seconds". Could be a stable network, though, but it might be worth trying to swap "commercial" server for another forwardproxy and see how that performs in comparison.
