### ISSUE TITLE
caddyfile multiple sites

### ISSUE THREAD

**Issue by zzeesstt** [caddyserver/forwardproxy#46]
Good afternoon.
I need to run this configuration, but it does not work. I think that there is a mistake.
Could you explain what I'm doing wrong?

https://1.example.com
tls self_signed
proxy / localhost:3000 {
websocket
transparent
}
https://2.example.com
tls self_signed
proxy / localhost:3001 {
websocket
transparent
}

**Comment by sergeyfrolov** [comment]
You are using `proxy`. This repo is for `forwardproxy`, which is a totally different type of proxy.
I suggest you request help at https://caddy.community/
