### ISSUE TITLE
Auto-generated PAC file: improve based on SwitchyOmega practices

### ISSUE THREAD

**Issue by sergeyfrolov** [caddyserver/forwardproxy#5]
The javascript below is generated by SwitchyOmega. It does some sorcery and then specifies that connections to localhost shouldn't go via proxy.

Would be nice to figure out what exactly is going on and, at least, allow users to access localhost directly.

SwitchyOmega auto-generated PAC file:
```javascript
﻿var FindProxyForURL = function(init, profiles) {
    return function(url, host) {
        "use strict";
        var result = init, scheme = url.substr(0, url.indexOf(":"));
        do {
            result = profiles[result];
            if (typeof result === "function") result = result(url, host, scheme);
        } while (typeof result !== "string" || result.charCodeAt(0) === 43);
        return result;
    };
}("+proxy", {
    "+proxy": function(url, host, scheme) {
        "use strict";
        if (/^127\.0\.0\.1$/.test(host) || /^::1$/.test(host) || /^localhost$/.test(host)) return "DIRECT";
        return "HTTPS sfrolov.io:443";
    }
});
```

[For Reference] Current auto-generated PAC file:
```javascript
function FindProxyForURL(url, host) {
	return "HTTPS %s:%s";
}
```

**Comment by bemasc** [comment]
This seems straightforward.  The relevant line is
```javascript
if (/^127\.0\.0\.1$/.test(host) || /^::1$/.test(host) || /^localhost$/.test(host)) return "DIRECT";
```
We could add a similar check to our PAC file and it should work fine.  (Although in our code I think we would use string equality, not this odd use of regex matching, which is probably the output of a code generator.)

**Comment by sergeyfrolov** [comment]
Yes, this part does seem straightforward, and good point that string equality would be better.
By "sorcery", I meant first half of this function, including function signature: I am not very proficient in js.

**Comment by bemasc** [comment]
That boilerplate is just for allowing their codegen system to make choices based on scheme, and to support multiple profiles.  It preprocesses the url to find the scheme, and looks up the policy function by profile name.  None of that is relevant to the goal of excluding localhost, which we can do just by adding that one line to return "DIRECT".

**Comment by sergeyfrolov** [comment]
Thanks for help!
