### ISSUE TITLE
How can I plug forwardproxy pluging into source code of Caddy ?

### ISSUE THREAD

**Issue by RunningToTheEdgeOfTheWorld** [caddyserver/forwardproxy#51]
What are you trying to do?
I am trying to develop the forwardproxy plugin to add some custom functions.
But I can't plug your plugin.

I have add import '_ "github.com/caddyserver/forwardproxy"' into run.go, but got error "___go_build_main_go flag redefined: https-port"

It suggest that have some conflict with "github.com/mholt/caddy/caddyhttp", both of plugin  use the args "https-port".
+++++++++++++++++++++++++++++++++++++++++++++++
/private/var/folders/2z/t_s4dwc130l7z3xq0mbdmppc0000gn/T/___go_build_main_go flag redefined: https-port
panic: /private/var/folders/2z/t_s4dwc130l7z3xq0mbdmppc0000gn/T/___go_build_main_go flag redefined: https-port

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc000094180, 0x1eaa680, 0x261d880, 0x1d7c6e2, 0xa, 0x1d89afc, 0x1d)
	/usr/local/go/src/flag/flag.go:805 +0x6e3
flag.StringVar(0x261d880, 0x1d7c6e2, 0xa, 0x1d76888, 0x3, 0x1d89afc, 0x1d)
	/usr/local/go/src/flag/flag.go:714 +0x99
github.com/caddyserver/forwardproxy/vendor/github.com/mholt/caddy/caddyhttp/httpserver.init.1()
	/Users/sweetdreams/go/src/github.com/caddyserver/forwardproxy/vendor/github.com/mholt/caddy/caddyhttp/httpserver/plugin.go:39 +0x73

**Comment by sergeyfrolov** [comment]
@RunningToTheEdgeOfTheWorld  from what I can see, the error is not related to forwardproxy itself: `github.com/caddyserver/forwardproxy/` does not even have `vendor` subfolder, but your machine seems to have it.
I just rebuilt Caddy on a completely fresh machine with Go 1.11.1 and added instructions to README:
https://github.com/caddyserver/forwardproxy#build-from-source
Do those instructions work for you?

**Comment by RunningToTheEdgeOfTheWorld** [comment]
Thanks, I remove my vendor subfolder, then it work~
This issues might be I use some Go package mangers and it cause the httpserver plugin upload twice.

**Comment by sergeyfrolov** [comment]
Glad that it works for you now!
Not sure what makes your package managers "cause the httpserver plugin upload twice", probably some sort of version mismatch
