### ISSUE TITLE
can find package

### ISSUE THREAD

**Issue by 344524488** [caddyserver/forwardproxy#54]
go get -d -u -t github.com/caddyserver/forwardproxy/... github.com/mholt/caddy/...
package github.com/caddyserver/forwardproxy
        imports github.com/lucas-clemente/quic-go/h2quic: cannot find package "github.com/lucas-clemente/quic-go/h2quic" in any of:
        /usr/local/go/src/github.com/lucas-clemente/quic-go/h2quic (from $GOROOT)
        /home/gopath/src/github.com/lucas-clemente/quic-go/h2quic (from $GOPATH)

**Comment by mholt** [comment]
Use `go get -d -u github.com/caddyserver/forwardproxy` instead -- that's all you need.

Make sure `GO111MODULE=on` if you are in your GOPATH.

**Comment by 344524488** [comment]
Good It is work now so thank you
