### ISSUE TITLE
the signature feature of anti probe does not work when deploying both forward proxy and reverse proxy

### ISSUE THREAD

**Issue by moralrebuild** [caddyserver/forwardproxy#61]
### 1. Is bug reproducible with [latest](https://caddyserver.com/download) `forwardproxy` build?
Yes

### 2. What are you trying to do?
setup both forward proxy and reverse proxy on the same node and each other with different SNI

### 3. What is your entire Caddyfile?
```
	(wildcard_cert) {
	  tls ${LETSENCRYPT_NOTIFICATION_EMAIL} {
	    dns cloudflare
	    wildcard
	  }
	}
	${REVERSE_PROXY_SERVER} {
	  import wildcard_cert
	  log stdout
	  errors stderr
	  root /var/www/ 
	  proxy /blog localhost:8080 {
	    websocket
	    header_upstream -Origin
	  }
	}
	${FORWARD_PROXY_SERVER} {
	  import wildcard_cert
	  log stdout
	  errors stderr
	  root /var/www/ 
	  forwardproxy {
	    basicauth ${USER} ${PASSWORD}
	    ports     80 443
	    hide_ip
	    hide_via
	    probe_resistance ${SECRET_LINK}
	    serve_pac ${PAC_FILE_NAME}
	    response_timeout 30
	    dial_timeout     30
	    acl {
	      allow     ::1/128 8.8.8.8 github.com *.github.io
	      deny      192.168.1.1/32 192.168.0.0/16 *.prohibitedsite.com *.localhost
	      allow     all
	      deny      all # unreachable rule, remaining requests are matched by 'allow all' above
	    }
	  }
	}

```

### 4. How is your client configured?
The SwitchyOmega chrome extension has been setup properly and could surf web via the HTTPS proxy server if comment out the line of 'probe_resistance'

### 6. Please paste any relevant HTTP request(s) here.

'''
CLOUDFLARE_EMAIL=$CLOUDFLARE_EMAIL CLOUDFLARE_API_KEY=$CLOUDFLARE_API_KEY /usr/local/bin/caddy -env -log stdout -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp
'''
### 7. What did you expect to see?
surf the internet without issue

### 8. What did you see instead (give full error messages and/or log)?
== The chrome browser
denies web access with error message 
```"ERR_TUNNEL_CONNECTION_FAILED"```

== Caddy console
```
22/Jun/2019:13:45:50 +0800 [ERROR 0 ] Proxy-Authorization is required! Expected format: <type> <credentials> 
```

**Comment by mholt** [comment]
Is this not an issue then?

**Comment by moralrebuild** [comment]
@mholt Thanks for your asking. I finally realized it had noting to do with the two kinds of proxy working together. In steady, it's the same issued reported in [issue 57](https://github.com/caddyserver/forwardproxy/issues/57)

**Comment by sergeyfrolov** [comment]
@moralrebuild when you say "same issue" do you mean ".localhost" probe resistance links not working with Chrome, probe_resistance not working at all, or forwardproxy not working altogether?
I am trying to reproduce the issue reported by @testcaoy7 later in #57, but haven't been able to do so: it works for me if I either
 - use Firefox
 - use a secret link that does not end with ".localhost"

**Comment by moralrebuild** [comment]
@sergeyfrolov 
I got the same result as you. Another thing need to mention is I could not have latest chrome to work even with the so called trick of launch parameter '--proxy-bypass-list="<-loopback>"' for secret link ending with ".localhost"
