### ISSUE TITLE
probe_resistance seems have bug

### ISSUE THREAD

**Issue by pexcn** [caddyserver/forwardproxy#64]
Here is my config:
```conf
https://<my_domain_name>:993 {
  gzip

  tls <my_email> {
    alpn h2
  }

  forwardproxy {
    basicauth <username> <password>
    probe_resistance hello.localhost
    hide_ip
    hide_via
  }

  log stdout
}
```

In port `443`, it works fine, but I set port to `993`, it can be connect via no auth.

**Comment by sergeyfrolov** [comment]
@pexcn 
Chrome no longer sends out requests for `.localhost` to proxy, which means that `.localhost` links should not be used for probe_resistance.
Please change the probe_resistance link to non-localhost address and use that.

**Comment by sergeyfrolov** [comment]
You may find more info in #57

**Comment by pexcn** [comment]
Thanks.
