### ISSUE TITLE
Does forwardproxy support ipv6 ?

### ISSUE THREAD

**Issue by wuzhongyi1105** [caddyserver/forwardproxy#67]
### 1. Is bug reproducible with [latest](https://caddyserver.com/download) `forwardproxy` build?
Yes

### 2. What are you trying to do?
Use ipv6 to visit websites.

### 3. What is your entire Caddyfile?
```text
forwardproxy {
    basicauth xxx xxxxxxx
    ports     80 443
    hide_ip
    hide_via
    probe_resistance
    response_timeout 30
    dial_timeout     30
```

### 4. How is your client configured?
Use Surge HTTPS Proxy.

### 5. How did you run Caddy? (give the full command and describe the execution environment). If multiple servers are used (for example with `upstream`), describe those as well.

In docker container.

### 7. What did you expect to see?
The proxy is working but only by ipv4, my server have ipv6 address and a shadowsocks proxy in another container can use ipv6 successful. I want to confirm if ipv6 is supported in forwardproxy.

**Comment by sergeyfrolov** [comment]
Yes, forwardproxy supports ipv6 fully.
