### ISSUE TITLE
Does it blindly forward the X-Forwarded-For header?

### ISSUE THREAD

**Issue by leshik** [caddyserver/forwardproxy#77]
Looks like it does.

I want to log incoming IP addresses, and as Caddy is in the container, I use `http.realip` for this. Requests are coming from AWS internal load balancer, which adds `X-Forwarded-For`, then they go outside.

I definitely don't want to forward `X-Forwarded-For`, and I have `hide_ip` enabled. Nevertheless, remote servers get my internal network IPs via `X-Forwarded-For`, which is not stripped from outgoing requests.

**Comment by sergeyfrolov** [comment]
Yes, it does blindly forward the header. Per README:
> hide_ip, if set, forwardproxy will not _add_ user's IP to "Forwarded:" header

so `hide_ip` does not intend to strip "X-Forwarded-For" header from HTTP responses that already have it.

A good way to support this use-case would be to add a new configuration option to specify headers that will be stripped.

**Comment by mholt** [comment]
Caddy has a `request_header` directive that can be used to manipulate the headers on the request; that might be useful in that case?

**Comment by leshik** [comment]
@mholt it's only in Caddy 2, right? With which this plugin isn't compatible yet.

**Comment by mholt** [comment]
Yeah, but that's basically all that matters at this point. It's working with Caddy 2 at #74 and Caddy 1 is no longer being developed.

I'd actually be OK with merging #74 after it is tested some more.

**Comment by leshik** [comment]
@mholt Interesting. I was under the impression that #74 is WIP and is a non-working state right now. If the only issue is testing, then I'll compile and give it a try.

**Comment by mholt** [comment]
@leshik Yep, well, both :) It's WIP but works. It _should_ have the same privacy guarantees as v1 but I haven't vetted those, there could definitely be some weaknesses that I haven't noticed as I ported it over. And there's no Caddyfile support yet, but that's easy to add.

So yes, please test it when you have a chance!

**Comment by leshik** [comment]
> And there's no Caddyfile support yet, but that's easy to add.

@mholt sorry what does it mean? I've seen your example config in #72 but I'm not sure how this works and where to put options such as `hide_ip`.

**Comment by mholt** [comment]
@leshik It means it can't be configured using the Caddyfile yet. Please see https://caddyserver.com/docs/getting-started to learn how to use Caddy 2.

**Comment by leshik** [comment]
@mholt I understand that Caddy 2 can be configured via JSON API, that's ok for my use case. Is it possible to configure the options of this plugin using the JSON API, or it is not implemented yet?

**Comment by mholt** [comment]
> Is it possible to configure the options of this plugin using the JSON API, or it is not implemented yet?

It is. That comes "for free" (i.e. no extra dev work needed) for all Caddy (v2) modules.

**Comment by leshik** [comment]
Ok, cool! I'll give it a try.

**Comment by leshik** [comment]
@mholt looks like it works. Just two things I haven't figured out:

1. How to make it use Caddy 2's existing basicauth module as you suggested in #74;
1. How to make Caddy log POST/PUT requests body.

Everything else works just fine.

**Comment by mholt** [comment]
Glad you got it working!

> How to make it use Caddy 2's existing basicauth module as you suggested in #74;

Just chain in an authentication handler: https://caddyserver.com/docs/json/apps/http/servers/routes/handle/authentication/

(For more questions about that, ask on our forum: https://caddy.community)

> How to make Caddy log POST/PUT requests body.

There is no way to do this efficiently, so it hasn't been implemented yet.

**Comment by leshik** [comment]
> Just chain in an authentication handler

Sure I did, it doesn't work as `Proxy-Authorization` header is used for proxy authentication and apparently this is not that Caddy authentication handler expects.

**Comment by mholt** [comment]
Oh... yeah forgot about that. I wonder if, as a temporary workaround, you could use Caddy's header manipulation features to copy the Proxy-Authorization header to Authorization and see if that works with it.

**Comment by leshik** [comment]
I personally don't need this feature, just have seen you mentioned it in the pull request and decided to test. Sure it will work, but will also pass the `Authorization` upstream, which is not a good thing.

**Comment by mholt** [comment]
You could also strip the header after the basicauth handler but before the forward_proxy handler.

Again, this is just my idea for a temporary workaround. It'd be nice to not re-implement the same auth logic twice, so we'll figure out a better way.

I'll close this issue then since we've gotten a bit off topic, and I think the original question can be addressed with Caddy's header features.
