### ISSUE TITLE
Hiding the proxy itself

### ISSUE THREAD

**Issue by OmgImAlexis** [caddyserver/forwardproxy#8]
Are there any plans on adding an option to hide the proxy server itself?

For example removing the `via` header. I know this would violate the HTTP 1.1 spec but some people may want this as some sites don't allow connections from proxies.

**Comment by sergeyfrolov** [comment]
@OmgImAlexis, we can hide the `via` header (btw, is it possible with existing Caddyfile syntax?)
Unfortunately, this won't be enough to hide the proxy, as there are numerous other such channels from TCP-related ones(timing, discrepancy between client and proxy tcp implementations, etc.) to WebRTC outright leaking the real IP address via STUN.
