### ISSUE TITLE
Seeing a crash while running caddy V2 with Forward Proxy Plugin (Branch: caddy2)

### ISSUE THREAD

**Issue by varmajee66** [caddyserver/forwardproxy#82]
### 1. Is bug reproducible with [latest](https://caddyserver.com/download) `forwardproxy` build?
 Yes

### 2. What are you trying to do?

I am trying to run Forward Proxy Plugin (caddy2 branch) (with Caddy Version 2) using the sample json mentioned in the doc just as a starting point. No specific scenario right now.

Below is how I got the binary:
=====================
./xcaddy build --with github.com/caddyserver/forwardproxy@8d6f47b4c4f3bdbecba34d9f65c8c5629ca0a5b3
2020/12/03 11:53:25 [INFO] Temporary folder: /tmp/buildenv_2020-12-03-1153.111340752
2020/12/03 11:53:25 [INFO] Writing main module: /tmp/buildenv_2020-12-03-1153.111340752/main.go
2020/12/03 11:53:25 [INFO] Initializing Go module
2020/12/03 11:53:25 [INFO] exec (timeout=10s): /usr/local/go/bin/go mod init caddy 
go: creating new go.mod: module caddy
2020/12/03 11:53:25 [INFO] Pinning versions
2020/12/03 11:53:25 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/caddyserver/caddy/v2 
go: github.com/caddyserver/caddy/v2 upgrade => v2.2.2
2020/12/03 11:53:26 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/caddyserver/forwardproxy@8d6f47b4c4f3bdbecba34d9f65c8c5629ca0a5b3 
go: github.com/caddyserver/forwardproxy 8d6f47b4c4f3bdbecba34d9f65c8c5629ca0a5b3 => v0.0.0-20201002031408-8d6f47b4c4f3
2020/12/03 11:53:29 [INFO] Build environment ready
2020/12/03 11:53:29 [INFO] Building Caddy
2020/12/03 11:53:29 [INFO] exec (timeout=0s): /usr/local/go/bin/go build -o /home/pvarma/build_caddy/caddy -ldflags -w -s -trimpath 
2020/12/03 11:53:31 [INFO] Build complete: caddy
2020/12/03 11:53:31 [INFO] Cleaning up temporary folder: /tmp/buildenv_2020-12-03-1153.111340752

$ ./caddy version
v2.2.2 h1:Ha3bvEvkb/GLGEX648/qI5zTt6uJCnfQhZHmZBxhzDY=

### 3. What is your entire Caddyfile?
$ cat Caddyfile 
:443, example.com
route {
  forward_proxy {
    ports     80 443
    hide_ip
    hide_via
    probe_resistance secret-link-kWWL9Q.com # alternatively you can use a real domain, such as caddyserver.com
    serve_pac        /secret-proxy.pac
    dial_timeout     30
    upstream         https://user:password@extra-upstream-hop.com
    acl {
      allow     *.caddyserver.com
      deny      192.168.1.1/32 192.168.0.0/16 *.prohibitedsite.com *.localhost
      allow     ::1/128 8.8.8.8 github.com *.github.io
      allow_file /path/to/whitelist.txt
      deny_file  /path/to/blacklist.txt
      allow     all
      deny      all # unreachable rule, remaining requests are matched by `allow all` above
    }
  }
  file_server
}

### 4. How is your client configured?
No Client configured, just running caddy in beginning is giving the crash.

### 5. How did you run Caddy? (give the full command and describe the execution environment). If multiple servers are used (for example with `upstream`), describe those as well.

$ ./caddy run

### 6. Please paste any relevant HTTP request(s) here.
NA

### 7. What did you expect to see?
It should run without errors or should point out the error gracefully instead of stack trace.

### 8. What did you see instead (give full error messages and/or log)?

$ ./caddy run
2020/12/03 06:24:26.691	INFO	using adjacent Caddyfile
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8d55fe]

goroutine 1 [running]:
go.uber.org/zap.(*Logger).check(0x0, 0xc00095df01, 0x17a43ea, 0x4e, 0x16)
	go.uber.org/zap@v1.15.0/logger.go:263 +0x90e
go.uber.org/zap.(*Logger).Warn(0x0, 0x17a43ea, 0x4e, 0x0, 0x0, 0x0)
	go.uber.org/zap@v1.15.0/logger.go:194 +0x44
github.com/caddyserver/forwardproxy.(*Handler).UnmarshalCaddyfile(0xc000526900, 0xc0000f03f0, 0x203000, 0x203000)
	github.com/caddyserver/forwardproxy@v0.0.0-20201002031408-8d6f47b4c4f3/forwardproxy.go:768 +0xfc6
github.com/caddyserver/forwardproxy.parseCaddyfile(0xc0000f03f0, 0xc0000f0060, 0xc000335890, 0xc0007f2a80, 0xc0000f03c0, 0xc0007f2a40, 0x2, 0x2, 0xc0007f2a60, 0x1, ...)
	github.com/caddyserver/forwardproxy@v0.0.0-20201002031408-8d6f47b4c4f3/forwardproxy.go:875 +0x4a
github.com/caddyserver/caddy/v2/caddyconfig/httpcaddyfile.RegisterHandlerDirective.func1(0xc0000f03f0, 0xc0000f0060, 0xc000335890, 0xc0007f2a80, 0xc0000f03c0, 0xc0007f2a40, 0x2, 0x2, 0xc0007f2a60, 0x1, ...)
	github.com/caddyserver/caddy/v2@v2.2.2/caddyconfig/httpcaddyfile/directives.go:119 +0x20e
github.com/caddyserver/caddy/v2/caddyconfig/httpcaddyfile.parseSegmentAsConfig(0xc0000f0300, 0xc0000f0060, 0xc000335890, 0xc0007f2a80, 0xc0000f02d0, 0xc0007f2a40, 0x2, 0x2, 0xc0007f2a60, 0x1, ...)
	github.com/caddyserver/caddy/v2@v2.2.2/caddyconfig/httpcaddyfile/directives.go:333 +0x90f
github.com/caddyserver/caddy/v2/caddyconfig/httpcaddyfile.parseRoute(0xc0000f0300, 0xc0000f0060, 0xc000335890, 0xc0007f2a80, 0xc0000f02d0, 0xc0007f2a40, 0x2, 0x2, 0xc0007f2a60, 0x1, ...)
	github.com/caddyserver/caddy/v2@v2.2.2/caddyconfig/httpcaddyfile/builtins.go:520 +0x72
github.com/caddyserver/caddy/v2/caddyconfig/httpcaddyfile.RegisterHandlerDirective.func1(0xc0000f0300, 0xc0000f0060, 0xc000335890, 0xc0007f2a80, 0xc0000f02d0, 0xc0007f2a40, 0x2, 0x2, 0xc0007f2a60, 0x1, ...)
	github.com/caddyserver/caddy/v2@v2.2.2/caddyconfig/httpcaddyfile/directives.go:119 +0x20e
github.com/caddyserver/caddy/v2/caddyconfig/httpcaddyfile.ServerType.Setup(0xc0000f0030, 0x1, 0x1, 0xc000335890, 0xc0007f2a60, 0x1, 0x1, 0x0, 0x0, 0x0)
	github.com/caddyserver/caddy/v2@v2.2.2/caddyconfig/httpcaddyfile/httptype.go:171 +0x2591
github.com/caddyserver/caddy/v2/caddyconfig/caddyfile.Adapter.Adapt(0x1a349e0, 0x2663508, 0xc0000ec000, 0x2d6, 0x4d6, 0xc000335890, 0xc0001bb680, 0xa00000001680000, 0xc00095f670, 0xa7286e93dfa3bb1, ...)
	github.com/caddyserver/caddy/v2@v2.2.2/caddyconfig/caddyfile/adapter.go:49 +0x139
github.com/caddyserver/caddy/v2/cmd.loadConfig(0x171c8e0, 0x9, 0x0, 0x0, 0xc000093920, 0xc0006a0a50, 0x151e3e0, 0x8, 0xc00095fa20, 0x30093000040d218, ...)
	github.com/caddyserver/caddy/v2@v2.2.2/cmd/main.go:173 +0x28c
github.com/caddyserver/caddy/v2/cmd.cmdRun(0xc000082420, 0x0, 0x0, 0x0)
	github.com/caddyserver/caddy/v2@v2.2.2/cmd/commandfuncs.go:205 +0xcae
github.com/caddyserver/caddy/v2/cmd.Main()
	github.com/caddyserver/caddy/v2@v2.2.2/cmd/main.go:85 +0x239
main.main()
	caddy/main.go:12 +0x20

### 9. How can someone who is starting from scratch reproduce the bug as minimally as possible?

Below is how I got the binary:
=====================
./xcaddy build --with github.com/caddyserver/forwardproxy@8d6f47b4c4f3bdbecba34d9f65c8c5629ca0a5b3
2020/12/03 11:53:25 [INFO] Temporary folder: /tmp/buildenv_2020-12-03-1153.111340752
2020/12/03 11:53:25 [INFO] Writing main module: /tmp/buildenv_2020-12-03-1153.111340752/main.go
2020/12/03 11:53:25 [INFO] Initializing Go module
2020/12/03 11:53:25 [INFO] exec (timeout=10s): /usr/local/go/bin/go mod init caddy 
go: creating new go.mod: module caddy
2020/12/03 11:53:25 [INFO] Pinning versions
2020/12/03 11:53:25 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/caddyserver/caddy/v2 
go: github.com/caddyserver/caddy/v2 upgrade => v2.2.2
2020/12/03 11:53:26 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/caddyserver/forwardproxy@8d6f47b4c4f3bdbecba34d9f65c8c5629ca0a5b3 
go: github.com/caddyserver/forwardproxy 8d6f47b4c4f3bdbecba34d9f65c8c5629ca0a5b3 => v0.0.0-20201002031408-8d6f47b4c4f3
2020/12/03 11:53:29 [INFO] Build environment ready
2020/12/03 11:53:29 [INFO] Building Caddy
2020/12/03 11:53:29 [INFO] exec (timeout=0s): /usr/local/go/bin/go build -o /home/pvarma/build_caddy/caddy -ldflags -w -s -trimpath 
2020/12/03 11:53:31 [INFO] Build complete: caddy
2020/12/03 11:53:31 [INFO] Cleaning up temporary folder: /tmp/buildenv_2020-12-03-1153.111340752

**Comment by mholt** [comment]
Why was this closed?
