### ISSUE TITLE
Caddy2 support not only 443 port

### ISSUE THREAD

**Issue by snadn** [caddyserver/forwardproxy#87]
why v2 only support 443 port? can support other port?

> In the Caddyfile the addresses must start with :443 for the forward_proxy to work for proxy requests of all origins.

https://github.com/caddyserver/forwardproxy/blob/caddy2/README.md?plain=1#L19

**Comment by mholt** [comment]
Because 443 is the HTTPS port, so pretty much every site you visit with HTTPS will be on port 443; and I think that's also due to limitations in the proxy clients and their configuration possibilities.

**Comment by snadn** [comment]
@mholt I think that when Caddy acts as an https proxy, the domain in the configuration is necessary, and the port can be set arbitrarily. The desired configuration is as follows:
```
https://example.com:xxxx {
  forward_proxy {
    ...
  }
}
```
The proxy configuration takes effect only when accessing the domain name specified in the configuration. The configuration of Caddy v1 can meet expectations, but v2 cannot.V2 can take effect with any configured domain name access.
