### ISSUE TITLE
Download not available 

### ISSUE THREAD

**Issue by spuder** [caddyserver/forwardproxy#93]
According to [the installation documentation](https://github.com/caddyserver/forwardproxy#get-forwardproxy), to install this plugin a user must: 

>Download prebuilt binary
>Binaries are at https://caddyserver.com/download
>Don't forget to add http.forwardproxy plugin.

Yet when searching `https://caddyserver.com/download` , there is no plugin named `http.forwardproxy`

How is a user supposed to install this plugin? 

I'll gladly fix the documentation if you can point me at the correct location to install this plugin.

**Comment by samstride** [comment]
@spuder , the plugin is only available for caddy and not caddy2.

You can [follow this thread](https://github.com/caddyserver/forwardproxy/issues/72) where users have queried about caddy2 support.

Thanks.

**Comment by mholt** [comment]
Yeah, sorry; the `caddy2` branch has something usable, I think. But it's just not quite finished yet.
